# for WSL

## exec copy
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "iconv -f UTF-8 -t UTF-16LE | clip.exe"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "iconv -f UTF-8 -t UTF-16LE | clip.exe"
